# Generated by Django 4.2.5 on 2023-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Действующий'), (False, 'Заблокирован')], default=True, verbose_name='Статус пользователя'),
        ),
    ]
