# Generated by Django 4.2.5 on 2023-09-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('client_first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('client_last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('client_comment', models.CharField(max_length=150, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('client_email',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date_time', models.DateTimeField(verbose_name='дата-время')),
                ('log_status', models.CharField(choices=[('отправлено', 'отправлено'), ('не отправлено', 'не отправлено')], max_length=20, verbose_name='Статус')),
                ('log_server_answer', models.TextField(verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('log_date_time',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('mailing_time_start', models.DateTimeField(verbose_name='начало рассылки')),
                ('mailing_time_finish', models.DateTimeField(verbose_name='окончание рассылки')),
                ('mailing_period', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно'), ('ежемесячно', 'ежемесячно')], max_length=20, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('создано', 'создано'), ('рассылается', 'рассылается'), ('остановлено', 'остановлено')], default='создано', max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=150, verbose_name='тема')),
                ('message_text', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('id',),
            },
        ),
    ]
