# Generated by Django 4.2.5 on 2023-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_mailing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('created', 'создано'), ('sent', 'рассылается'), ('stopped', 'остановлено')], default='created', max_length=20, verbose_name='статус'),
        ),
    ]
