# Generated by Django 4.2.5 on 2023-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
    ]
