# Generated by Django 4.2.5 on 2023-09-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_message_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.log', verbose_name='лог'),
        ),
    ]
