# Generated by Django 4.2.5 on 2023-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_mailing_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='mailing_client',
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
    ]
