# Generated by Django 4.2.5 on 2023-09-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_remove_mailing_mailing_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_status',
            field=models.BooleanField(choices=[('отправлено', 'отправлено'), ('не отправлено', 'не отправлено')], verbose_name='Статус'),
        ),
    ]
