# Generated by Django 4.2.5 on 2023-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_log_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_status',
            field=models.CharField(choices=[('отправлено', 'отправлено'), ('не отправлено', 'не отправлено')], max_length=20, verbose_name='Статус'),
        ),
    ]
